name: "Hello Actions"
description: "Greet someone"
author: "kuba.odias@relayr.io"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "aperture"
  color: "green"
